version: '3.8'

services:
  ci-test:
    build:
      context: .
      dockerfile: Dockerfile.ci
    volumes:
      - .:/workspace:cached
      - /workspace/__pycache__
      - /workspace/.pytest_cache
      - /workspace/.nox
    working_dir: /workspace
    environment:
      - FORCE_COLOR=1
      - UV_SYSTEM_PYTHON=1
      - PYTHONIOENCODING=utf-8
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    # Override default CMD to allow interactive use
    command: /bin/bash
    tty: true
    stdin_open: true

  ci-test-run:
    extends: ci-test
    # Run the exact same test as CI
    command: pytest tests/unit/ -m 'unit and not ci_exclude' --maxfail=3 --tb=short -x

  ci-test-specific:
    extends: ci-test
    # Run specific failing test
    command: pytest tests/unit/test_python_executor.py::TestManuscriptPathIntegration::test_manuscript_path_in_initialization_block -v
