# Release configuration for rxiv-maker
# This file can be modified to adjust release behavior without changing code

package_name: "rxiv-maker"

# PyPI configuration
pypi_timeout: 300  # 5 minutes max wait for PyPI propagation
pypi_check_interval: 30  # Check every 30 seconds

# GitHub configuration
github_timeout: 120  # 2 minutes max wait for GitHub API

# Cross-repository configuration
homebrew_repo: "homebrew-rxiv-maker"
apt_repo: "apt-rxiv-maker"
cross_repo_timeout: 600  # 10 minutes max wait for cross-repo workflows

# Retry configuration
max_retries: 3
backoff_factor: 2.0

# Repository URLs (for validation)
repositories:
  main: "https://github.com/henriqueslab/rxiv-maker"
  homebrew: "https://github.com/henriqueslab/homebrew-rxiv-maker"
  apt: "https://github.com/henriqueslab/apt-rxiv-maker"

# Notification configuration
notifications:
  discord_webhook: null  # Set via environment variable DISCORD_WEBHOOK
  slack_webhook: null    # Set via environment variable SLACK_WEBHOOK
