title:
  long: "Comprehensive Figure Positioning and Blindtext Examples for Rxiv-Maker"
  short: "Figure Positioning Examples"

authors:
  - name: "Example Author"
    affiliation: "Example University"
    email: "example@university.edu"

keywords: ["figure positioning", "blindtext", "latex", "examples"]

acknowledge_rxiv_maker: false

# Configuration specific to this example manuscript
example_manuscript: true
